### ISSUE TITLE
building deb packages hangs.

### ISSUE THREAD

**Issue by yusufilker** [150balbes/lib#23]
building deb packages hangs in terminal and there is an error in the log file:
ARMBIAN/output/debug/patching.log :
Processing file  ARMBIAN/lib/patch/kernel/amlogics905x-default/packaging-3.14-DEFAULT with-postinstall-scripts.patch
12 out of 14 hunks FAILED -- saving rejects to file scripts/package/builddeb.rej

**Comment by 150balbes** [comment]
How you set the compiler ? That would be going a way in the settings of the user that is collected, it is necessary to register in the PATH variable the directory with the compiler.

**Comment by yusufilker** [comment]
I was using Amlogic buildroot before.
The compiler set in /opt

echo $PATH
/opt/jdk1.7.0_65/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:**/opt/gnutools/arc2.3-p0/elf32-4.2.1/bin:/opt/gnutools/arc2.3-p0/uclibc-4.2.1/bin::/opt/arc-4.8-amlogic-20130904-r2/bin:/opt/CodeSourcery/Sourcery_G++_Lite/bin:/opt/CodeSourcery/Sourcery_G++_Lite/arm-none-eabi/bin:/opt/CodeSourcery/Sourcery_G++_Lite/arm-none-linux-gnueabi/bin:/opt/gcc-linaro-arm-linux-gnueabihf/bin:/opt/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux/bin:/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin**

**Comment by 150balbes** [comment]
With these parameters PATH when you run the script ./compile.sh he starts checking and installing the system standard compiler packages from online repositories (versions 4.7 and 4.8). These compilers are in the standard directories /usr/bin /usr/sbin . So if you invoke compile, they are found first. Need to change order of directories in the PATCH parameters. First on the list should be the compilers of the directory /opt.

echo $PATH

**/opt/gnutools/arc2.3-p0/elf32-4.2.1/bin:/opt/gnutools/arc2.3-p0/uclibc-4.2.1/bin::/opt/arc-4.8-amlogic-20130904-r2/bin:/opt/CodeSourcery/Sourcery_G++_Lite/bin:/opt/CodeSourcery/Sourcery_G++_Lite/arm-none-eabi/bin:/opt/CodeSourcery/Sourcery_G++_Lite/arm-none-linux-gnueabi/bin:/opt/gcc-linaro-arm-linux-gnueabihf/bin:/opt/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux/bin:/opt/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin:**/opt/jdk1.7.0_65/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by 150balbes** [comment]
By the way, I use the instructions in the user settings which harvested only one catalog compiler

export PATCH=/opt/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux/bin:$PATCH

**Comment by yusufilker** [comment]
Thank you very much for help,

I changed the PATH variable but result is the same, I think the problem is the builddeb patch  `/lib/patch/kernel/amlogics905x-default/packaging-3.14-DEFAULT with-postinstall-scripts.patch`

The patch is not applied correctly. I put screenshots of failed patch, dpkg-deb hangs and I can exit with control-c.  I put patch results builddeb & builddeb.orig & builddeb.rej files inside the zip file.


![hang](https://cloud.githubusercontent.com/assets/6896503/19656558/32bbfe6c-9a29-11e6-93e5-395a5db777f4.png)
![patch_failed](https://cloud.githubusercontent.com/assets/6896503/19656559/32c363dc-9a29-11e6-9d99-064a8a4445e4.png)
[kernel_patch_results.zip](https://github.com/150balbes/lib/files/546606/kernel_patch_results.zip)

**Comment by 150balbes** [comment]
What user runs the Assembly ? You need to run as root.

```
$  sudo su
#  ./compile.sh
```

**Comment by 150balbes** [comment]
Judging by the screenshots, you're trying to collect from a normal user ? Need to collect as root. After starting the virtual machine, I launch the terminal and immediately proceed under root (sudo su) and all actions performed under root. The warning in the patch can not pay attention to everything going. By the way, when you build u-boot it will be the same compile error, do not pay attention, the package is assembled correctly. This is due to the fact that some files for u-boot already assembled (ready-made binaries) and they are properly popadaut in the Assembly.24.10.2016, 20:39, "yusufilker" <notifications@github.com>:Thank you very much for help,

I changed the PATH variable but result is the same, I think the problem is the builddeb patch  /lib/patch/kernel/amlogics905x-default/packaging-3.14-DEFAULT with-postinstall-scripts.patch

The patch is not applied correctly. I put screenshots of failed patch, dpkg-deb hangs and I can exit with control-c.  I put patch results builddeb & builddeb.orig & builddeb.rej files inside the zip file.



kernel_patch_results.zip

**Comment by yusufilker** [comment]
Yes, that is solved the problem:
I include only one compiler in the PATH:  /opt/gcc-linaro-aarch64-linux-gnu-4.9-2014.09_linux/bin
And I run as root. Now it compiles
Thanks again,
